---
title: "Map terrorism"
author: "Duc-Quang Nguyen | swissinfo.ch"
date: " 2016"
output: 
  html_document:
    toc: true
    toc_depth: 3
    theme: simplex
---

# Hexmap in R

* [ggplot2](http://unconj.ca/blog/custom-hexbin-functions-with-ggplot.html)

```{r setup, include=FALSE}
data.file <- "input/GTD_0617dist.csv"
euro_events.file <- "input/terrorism world map - europeanEvents.csv"
translation.file <- "input/terrorism world map and area chart - Sheet1.csv"

lang2exclude <- c('AR', 'FR', 'DE', 'IT', 'RU', 'PT', 'ES', 'EN')

dev <- F
cleanOutput <- F

library(tidyverse)
library(magrittr)
library(stringr)
library(knitr)
library(countrycode)
library(swiMap)
library(swiTheme)

### Interactive 
library(htmltools)
library(swiRcharts)
library(highcharter)

### Mapping 
require(rgdal)
require(rgeos)
require(maptools)
### Misc stuff
require(viridis)
```

```{r load, echo=F}
data <- read_csv(data.file) 
txt <- loadTranslation(translation.file)
if(length(lang2exclude) > 0) {
  warning("\nAbout to discard languages: ", lang2exclude)
  txt <- txt[,-match(lang2exclude, colnames(txt)), drop = F]
  warning("\nLeft in txt:", colnames(txt))
}
euro <- read_csv(euro_events.file)

stopifnot(euro$id %in% rownames(txt))

# get the list of coutries
countries <- data %>% select(country, country_txt) %>% 
  distinct() %>% arrange(country) 

regions <- data %>% select(region, region_txt) %>% 
  distinct() %>% arrange(region) 

data %<>% select(-region_txt)

# load world map data
world <- map_data("world") %>% filter(region != "Antarctica")
#world <- world[!world$region %in% c("Antarctica", "Lesotho"),] # intercourse antarctica
#world %<>% filter(region != "South Africa" | (region == "South Africa" & (subregion != "hole" | is.na(subregion)))
```

```{r animated map}
library(ggrepel)
library(animation)
library(grid)

dm <- data %>% filter(iyear >= 2012, nkill > 0, !is.na(longitude)) %>% 
  select(iyear, imonth, iday, country_txt, latitude, longitude, nkill) %>%
  rename(lat = latitude, lon = longitude, z = nkill)

dm %<>% mutate(
  date = str_c(iyear, imonth, iday, sep = "-") %>% as.Date(),
  yearMonth = format(date, "%Y-%m")
) %>% as.data.frame()
rownames(dm) <- 1:nrow(dm)

euro %<>% mutate(
  date = str_c(iyear, imonth, iday, sep = "-") %>% as.Date(),
  yearMonth = format(date, "%Y-%m")
)

deathsByMonth <- dm %>% group_by(yearMonth) %>% 
  summarise(
    monthtot = sum(z),
    monthatt = length(z)
  ) %>% 
  ungroup() %>%
  mutate(tot = cumsum(monthtot), totatt = cumsum(monthatt))

#xlim <- quantile(dm$lon, probs = c(0, .99), na.rm = T) + c(-5, 5)
xlim <- c(-129, 129)
#xlim <- c(-89, 149)
ylim <- c(-60, 140) #quantile(dm$lat, probs = c(0, 1), na.rm = T) + c(-1, 1)
topMargin <- 30

top_countries <- dm %>% group_by(country_txt) %>%
  summarise(tot = sum(z)) %>% ungroup() %>%
  arrange(desc(tot)) %>% head(30) %>% .$country_txt

labels <- dm %>% filter(country_txt %in% top_countries) %>%
  group_by(country_txt) %>%
  summarise(lat = mean(lat), lon = mean(lon)) %>%
  ungroup()
  
labels %<>% filter(
  country_txt %in%
  c("Iraq", "Afghanistan", "Nigeria", "Syria", 
    "Pakistan", "Yemen", "Somalia", "Libya", "India", 
    "Philippines", "Ukraine",  "South Sudan", "Egypt", 
    "Colombia", "Turkey")) %>%
  mutate(iso2 = countrycode(country_txt, "country.name", "iso2c"))
stopifnot(!all(is.na(labels$iso2)))


ym <- "2015-01"
lang <- 'FR'

# Code to override clipping
# https://stackoverflow.com/questions/37890638/how-to-change-font-size-in-geom-text-outside-plot-area
clipGg <- function(gg) {
  gt <- ggplot_gtable(ggplot_build(gg))
  gt$layout$clip[gt$layout$name == "panel"] <- "off"
  grid.draw(gt)
}


plotSingleTime <- function(dm, labels, euro, ym, txt, lang) {
  
  dd <- dm %>% filter(yearMonth == ym)
  bg <- dm %>% filter(yearMonth < ym)
  stats.label <- deathsByMonth %>% filter(yearMonth == ym)
  euro.label <- euro %>% filter(yearMonth == ym)
  sizeLabel <- if(lang %in% c('ZH', 'JA')) 5.5 else 7
  themeFontSize <- if(lang %in% c('ZH', 'JA')) 30 else 37
    
  # translation & text
  if(nrow(euro.label) > 0) {
    euro.label %<>% mutate(label = txt[euro.label$id, lang])
  }
  
  labels %<>% mutate(
    label = countryTranslation(iso2, lang)[,2]
  )
  
  yearMonth <- paste0(
        dd[1, 'iyear'], " ", txt[as.character(dd[1, 'imonth']), lang]
  )
  subtitle <- paste0(
    format(stats.label$monthtot, big.mark = "'"), " ", txt['descr1', lang], ", ",
    format(stats.label$monthatt, big.mark = "'"), " ", txt['descr1b', lang]
  )
  
  subtitle2 <- paste0(  
    "(", txt['descr2', lang], " ", format(stats.label$tot, big.mark = "'"), ', ', 
    format(stats.label$totatt, big.mark = "'"), ")"
  )

  caption <- paste0(txt['source', lang], ": ", txt['source.name', lang], " | swissinfo.ch | @duc_qn  ")
  
  p <- ggplot() + 
    swi_dark_map(base_size = themeFontSize, base_family = txt['base.font', lang], 
                 title_family = txt['title.font', lang], subtitle_family = txt['base.font', lang]) + 
    geom_map(
      data=world, map=world,
      aes(x=long, y=lat, map_id=region),
      color="#4d4d4d", fill= "#262626", size=0.35, alpha=0.85) +
    coord_map(xlim = xlim, ylim = ylim, projection = "mollweide") + 
    geom_jitter(data = bg, aes(x = lon, y= lat, size = z, 
                               alpha = (difftime(bg$date, min(bg$date)) / (3600 * 24)) %>% as.numeric()), 
                stroke = 0, colour = "#6a332f") +
    geom_jitter(data = dd, aes(x = lon, y= lat, size = z), 
                alpha=0.6, stroke = 0, colour = "#d09995") +
    scale_size_continuous(
      trans = "log1p", range = c(10^-8, 9), 
      breaks = c(10, 100, 1000), limits = range(dm$z), 
      guide = guide_legend(override.aes = list(fill = "#d09995"), title = txt['descr1', lang])) +
    scale_alpha_continuous(range = c(0.001, 0.1), guide = F) +
    theme(
      legend.key.size = unit(2, "lines"),
      legend.position = c(0.05,0.07),
      legend.key.height = unit(2.8, "lines"),
      plot.title = element_text(hjust = 0.5, colour = "#f2f2f2",
                                margin=margin(b=topMargin, t = 10), 
                                size =  44),
      plot.subtitle = element_text(hjust = 0.5, size = 50),
      plot.margin = unit(c(0.5, 0, 0.2, 0), "cm"),
      plot.background = element_rect(fill = "#595959", size = 0, color = "#595959"),
      panel.background = element_rect(fill = "#595959", size = 0, color =  "#595959"),
      plot.caption = element_text(size = 26, hjust=1, margin=margin(t=13, b=10, r=25), color = '#f2f2f2')
    ) + 
    geom_text_repel(
      data = labels, aes(x = lon, y = lat, label = label), 
      colour = "white", segment.alpha = 0.6, force = 2,
      alpha = 0.9, nudge_x = -9, nudge_y = -6.6, family = txt['base.font', lang], size = sizeLabel) +
    labs(title = txt['title', lang], caption = caption, subtitle = paste0(yearMonth, "  ", subtitle))
  
  p <- p + annotate(geom = "text", x = 0, y = 85, label = subtitle2,
                    family = txt['base.font', lang], size = 11, 
                    colour = "white", hjust = 0.5, vjust = 1, alpha = 0.8)
   #print(p)
  if(nrow(euro.label) > 0) {
    p2 <- p + 
      geom_text_repel(
       data = euro.label, aes(x = lon, y = lat, label = label), 
        colour = "white", segment.alpha = 0.6, force = 2,
        alpha = 0.95, nudge_x = 5, nudge_y = 6, family = txt['base.font', lang], size = sizeLabel)
    print(p2)
  } else {
    print(p)
  }
}

#plotSingleTime(dm, labels, euro, ym, txt, lang)


if(dev) {
  yearMonths <- unique(dm$yearMonth) %>% tail(3)  
  txt <- txt[,'FR', drop = F]
} else {
  yearMonths <- c(unique(dm$yearMonth), rep(dm$yearMonth %>% tail(1), 3))
}

for(lang in colnames(txt)) {
  cat("\n\tMapping ", lang)
  gif.output <- paste0("terrorismDeathMap_", lang, ifelse(dev == T, "_dev", ""), ".gif")
  html.output <- paste0("terrorismDeathMap_", lang, ifelse(dev == T, "_dev", ""), ".html")
  saveGIF({
    for(ym in yearMonths) {
      plotSingleTime(dm, labels, euro, ym, txt, lang)
    }
  },  movie.name = gif.output, 
  interval = 1, ani.width = 660 * 2, ani.height = 660 * 1.55, loop = TRUE)
  
  save_html(
    tags$html(
    # tags$head(includeCSS("image.css")),
      tags$body(    
        div(img(src = gif.output, width= "100%")),
        HTML(iframeresizer)  
      )), file = html.output, libdir = "js"#, background = '#1A0100'
  )
    
    
}

```

```{r find events only in Europe, eval = F}
if(dev) {
 ddd <- data %>% filter(iyear >= 2012, nkill > 0, !is.na(longitude)) %>%
   filter(region == 8) %>% arrange(desc(nkill)) %>% 
   select(-contains("crit"), -contains("natlty"),  -property, -propvalue, -ishostkid, -nhostkid)
 ddd %>% filter(eventid != 201605190058) %>% arrange(desc(nkill)) %>% head(11) %>% View()
 
 
 ddd %>% filter(eventid != 201605190058) %>% head(11) %>% 
   mutate(
     date = str_c(iyear, imonth, iday, sep = "-") %>% as.Date(),
     yearMonth = format(date, "%Y-%m")
  ) %>% ungroup() %>%
   group_by(date, yearMonth) %>%
   summarise(lat = mean(latitude), lon = mean(longitude), country = unique(country_txt)) %>% ungroup()   
   write_csv(path = "~/Desktop/tmp.csv")
}

```




```{r hexgrid map, eval=F}
dm.expanded <- dm[rep(row.names(dm), dm$z), ]
sum(dm$z[which(dm$z > 1)]) + nrow(dm)

  
ggplot(dm.expanded %>% filter(iyear == 2016), aes(x=lon,y=lat)) + 
  stat_binhex(bins=50) + 
  coord_map(xlim = xlim, ylim = ylim, projection = "gilbert") + 
  scale_fill_viridis(trans = "log")

```



```{r move production graphics}
if(cleanOutput) {
  files <- c("basename_.*html", "js")

  if(!dir.exists("output/bak")) {
    dir.create("output/bak")
  } else {
    list.files("output/bak/", full.names = T, recursive = T) %>% file.remove()
  }
  ori.files <- list.files("output", full.names = T)[list.files("output") != "bak"]
  file.copy(ori.files, to = "output/bak/", recursive = T)
  unlink(ori.files, recursive = T)

  files_tomove <- lapply(files, function(x) list.files(pattern = x)) %>% unlist()
  file.copy(files_tomove, "output", recursive = T)
  unlink(files_tomove, recursive = T)
}


```
